version: '3.1'

#Docker Compose file to run Centrify Centos Image
#Author: Felderi Santiago
#Date: 01/09/2018

services: 
  cjoin:
      image: 'centrifydavid/centrifytesting'
      ports:
        - '2020:22'
      environment:
        - 'PORT=2020'
        - 'LOGIN_ROLE=AUTHORIZED_ROLE_HERE'
        - 'CONNECTOR=CONNECTOR_ID_HERE'
        - 'TENANT_URL=cloud.centrify.com'
        - 'CODE=<CODE GOES HERE>'
      volumes: 
        - /sys/fs/cgroup:/sys/fs/cgroup
      cap_add:
        - SYS_ADMIN
        