version: '3.1'

#Docker Compose file to run Centrify Centos Image
#Author: Felderi Santiago
#Date: 01/09/2018

services: 
  cjoin:
      image: 'centrifydavid/centrifytesting'
      ports:
        - '2020:22'
      environment:
        - 'PORT=2020'
        - 'LOGIN_ROLE=UnixUsers'
        - 'CONNECTOR=DC1'
        - 'TENANT_URL=davidmcneely.my-qa.centrify.com'
        - 'CODE=A7C9B8CC-874B-4E3A-AFFB-051B0F91BDE8'
      volumes: 
        - /sys/fs/cgroup:/sys/fs/cgroup
      cap_add:
        - SYS_ADMIN
        